steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/codi-be-test:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/codi-be-test:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'codi-be-test'
    - '--image'
    - 'gcr.io/$PROJECT_ID/codi-be-test:$COMMIT_SHA'
    - '--region'
    - 'asia-northeast3'
images:
  - 'gcr.io/$PROJECT_ID/codi-be-test:$COMMIT_SHA'
logsBucket: 'gs://mylogsbucket'
options:
  logging: NONE
